!code-insiders --install-extension akamud.vscode-theme-onedark
!code-insiders --install-extension akamud.vscode-theme-onelight
!code-insiders --install-extension albert.TabOut
!code-insiders --install-extension alefragnani.project-manager
!code-insiders --install-extension AlexTi.intellij-idea-light-theme
!code-insiders --install-extension AndrewZhang.scribeai
!code-insiders --install-extension aslamanver.vsc-export
!code-insiders --install-extension azemoh.one-monokai
!code-insiders --install-extension batisteo.vscode-django
!code-insiders --install-extension cmoog.sqlnotebook
!code-insiders --install-extension cweijan.vscode-office
!code-insiders --install-extension DanielSanMedium.dscodegpt
!code-insiders --install-extension donjayamanne.python-environment-manager
!code-insiders --install-extension donjayamanne.python-extension-pack
!code-insiders --install-extension dracula-theme.theme-dracula
!code-insiders --install-extension eamodio.gitlens
!code-insiders --install-extension esbenp.prettier-vscode
!code-insiders --install-extension felipecaputo.git-project-manager
!code-insiders --install-extension fisheva.eva-theme
!code-insiders --install-extension formulahendry.code-runner
!code-insiders --install-extension GitHub.github-vscode-theme
!code-insiders --install-extension GitHub.remotehub
!code-insiders --install-extension GitHub.vscode-pull-request-github
!code-insiders --install-extension GrapeCity.gc-excelviewer
!code-insiders --install-extension Horla.horla-light-theme
!code-insiders --install-extension intellsmi.comment-translate
!code-insiders --install-extension jaaxxx.multicursor-casepreserve
!code-insiders --install-extension janisdd.vscode-edit-csv
!code-insiders --install-extension johnpapa.vscode-peacock
!code-insiders --install-extension johnpapa.winteriscoming
!code-insiders --install-extension KevinRose.vsc-python-indent
!code-insiders --install-extension magicstack.MagicPython
!code-insiders --install-extension marp-team.marp-vscode
!code-insiders --install-extension mechatroner.rainbow-csv
!code-insiders --install-extension mhutchie.git-graph
!code-insiders --install-extension monokai.theme-monokai-pro-vscode
!code-insiders --install-extension ms-azuretools.vscode-docker
!code-insiders --install-extension MS-CEINTL.vscode-language-pack-ko
!code-insiders --install-extension ms-dotnettools.dotnet-interactive-vscode
!code-insiders --install-extension ms-edgedevtools.vscode-edge-devtools
!code-insiders --install-extension ms-python.black-formatter
!code-insiders --install-extension ms-python.gather
!code-insiders --install-extension ms-python.isort
!code-insiders --install-extension ms-python.python
!code-insiders --install-extension ms-python.vscode-pylance
!code-insiders --install-extension ms-toolsai.jupyter
!code-insiders --install-extension ms-toolsai.jupyter-keymap
!code-insiders --install-extension ms-toolsai.jupyter-renderers
!code-insiders --install-extension ms-toolsai.vscode-jupyter-cell-tags
!code-insiders --install-extension ms-toolsai.vscode-jupyter-powertoys
!code-insiders --install-extension ms-toolsai.vscode-jupyter-slideshow
!code-insiders --install-extension ms-vscode-remote.remote-containers
!code-insiders --install-extension ms-vscode-remote.remote-ssh
!code-insiders --install-extension ms-vscode-remote.remote-ssh-edit
!code-insiders --install-extension ms-vscode-remote.remote-wsl
!code-insiders --install-extension ms-vscode-remote.vscode-remote-extensionpack
!code-insiders --install-extension ms-vscode.powershell
!code-insiders --install-extension ms-vscode.remote-explorer
!code-insiders --install-extension ms-vscode.remote-repositories
!code-insiders --install-extension ms-vscode.remote-server
!code-insiders --install-extension ms-vsliveshare.vsliveshare
!code-insiders --install-extension msnilshartmann.blue-light
!code-insiders --install-extension mtxr.sqltools
!code-insiders --install-extension mtxr.sqltools-driver-mysql
!code-insiders --install-extension njpwerner.autodocstring
!code-insiders --install-extension njqdev.vscode-python-typehint
!code-insiders --install-extension nonoroazoro.syncing
!code-insiders --install-extension oderwat.indent-rainbow
!code-insiders --install-extension Oracle.mysql-shell-for-vs-code
!code-insiders --install-extension phoihos.csv-to-md-table
!code-insiders --install-extension phplasma.csv-to-table
!code-insiders --install-extension PKief.material-icon-theme
!code-insiders --install-extension rahmanyerli.ra-spring
!code-insiders --install-extension RandomFractalsInc.vscode-data-preview
!code-insiders --install-extension RandomFractalsInc.vscode-data-table
!code-insiders --install-extension redhat.vscode-yaml
!code-insiders --install-extension renxzen.google-colab-theme
!code-insiders --install-extension sam-the-programmer.jupyter-theme
!code-insiders --install-extension SBSnippets.pytorch-snippets
!code-insiders --install-extension tanmay.discord-theme
!code-insiders --install-extension tomoki1207.pdf
!code-insiders --install-extension uloco.theme-bluloco-light
!code-insiders --install-extension vincaslt.highlight-matching-tag
!code-insiders --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
!code-insiders --install-extension VisualStudioExptTeam.vscodeintellicode
!code-insiders --install-extension VisualStudioExptTeam.vscodeintellicode-completions
!code-insiders --install-extension vscode-icons-team.vscode-icons
!code-insiders --install-extension waderyan.gitblame
!code-insiders --install-extension whizkydee.material-palenight-theme
!code-insiders --install-extension wholroyd.jinja
!code-insiders --install-extension Youssef.viow
!code-insiders --install-extension yzhang.markdown-all-in-one
!code-insiders --install-extension zhuangtongfa.material-theme
